name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main  # Run tests on pushes to the main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests targeting main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify a concrete version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=100
